apiVersion: apps/v1
kind: Deployment
metadata:
 name: calculator
 namespace: srinivas
spec:
 replicas: 2
 selector:
  matchLabels:
   app: calculator
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 50%
   maxSurge: 50%
 minReadySeconds: 30
 template:
  metadata:
   name: calculator
   labels:
    app: calculator
  spec:
   containers:
   - name: calculator
     image: krssrinivas/luckynumber:1
     resources:
      requests:
       cpu: "200m"
       memory: "200Mi"
      limits:
       cpu: "200m"
       memory: "200Mi"
     ports:
     - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: calculatorsvc
 namespace: srinivas
spec:
  selector:
   app: calculator
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000